#!/usr/bin/env python3
"""Generate the Wii U title name list (wiiu_titles_wiiubrew.go) for
account-proxy (Discord Rich Presence) and relay-admin (dashboard game names)
from a saved copy of WiiUBrew's title database
(https://wiiubrew.org/wiki/Title_database).

Run by hand when the list should be refreshed; nothing fetches it at runtime:

    curl -sS https://wiiubrew.org/wiki/Title_database -o /tmp/title_database.html
    python3 scripts/gen_wiiu_titles.py /tmp/title_database.html

Hand-curated names (account-proxy/discord_titles.go, relay-admin's
gameServerTitles) take precedence.
Games use the English (USA, else EUR) name for every regional version that
shares the product code, so Japanese releases show their English title.
"""
import datetime
import html
import os
import re
import sys

SECTIONS = ("00050010", "00050030", "00050000:")
OUTPUTS = ("account-proxy", "relay-admin")


def text(cell):
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", "", cell))).strip()


def main(path):
    page = open(path, encoding="utf-8").read()
    parts = re.split(r'<span class="mw-headline" id="([^"]*)"', page)
    rows = []  # (title id, name, product code, region)
    for i in range(1, len(parts), 2):
        if not parts[i].startswith(SECTIONS):
            continue
        body = parts[i + 1]
        table = body.split("</table>", 1)[0]
        head = [text(h) for h in re.findall(r"<th[^>]*>(.*?)</th>", table, re.S)]
        name_col = head.index("Name") if "Name" in head else head.index("Description")
        code_col = next(j for j, h in enumerate(head) if h.startswith("Product Code"))
        region_col = head.index("Region")
        versions_col = head.index("Versions")
        for tr in re.findall(r"<tr>(.*?)</tr>", table, re.S):
            cells = [text(c) for c in re.findall(r"<td[^>]*>(.*?)</td>", tr, re.S)]
            if len(cells) <= max(name_col, code_col, region_col, versions_col):
                continue
            m = re.fullmatch(r"([0-9A-Fa-f]{8})-([0-9A-Fa-f]{8})", cells[0])
            if not m or not cells[name_col]:
                continue
            versions = cells[versions_col]
            if versions and all("_DEV" in v for v in versions.split(",")):
                continue  # development builds only
            name = re.sub(r"\s*\(OSv\d+\)$", "", cells[name_col])
            rows.append((int(m.group(1) + m.group(2), 16), name, cells[code_col], cells[region_col]))

    # English name per game code (WUP-P-XXXR: XXX = game, R = region).
    english = {}
    for tid, name, code, region in rows:
        m = re.fullmatch(r"WUP-[A-Z]-([A-Z0-9]{3})([A-Z])", code)
        if not m:
            continue
        rank = {"USA": 0, "EUR": 1}.get(region, 9)
        if m.group(1) not in english or rank < english[m.group(1)][0]:
            english[m.group(1)] = (rank, name)

    names = {}
    for tid, name, code, region in rows:
        m = re.fullmatch(r"WUP-[A-Z]-([A-Z0-9]{3})([A-Z])", code)
        if m and m.group(1) in english and english[m.group(1)][0] < 9:
            name = english[m.group(1)][1]
        names.setdefault(tid, name)

    lines = [
        "// Code generated by scripts/gen_wiiu_titles.py from WiiUBrew's title database",
        f"// (snapshot {datetime.date.today().isoformat()}). DO NOT EDIT; curate names by hand elsewhere.",
        "",
        "package main",
        "",
        "var wiiubrewTitleNames = map[uint64]string{",
    ]
    lines += [f"\t0x{tid:016X}: {go_string(names[tid])}," for tid in sorted(names)]
    lines.append("}")
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for svc in OUTPUTS:
        with open(os.path.join(root, svc, "wiiu_titles_wiiubrew.go"), "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
    print(f"{len(names)} titles written for {', '.join(OUTPUTS)}")


def go_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


if __name__ == "__main__":
    main(sys.argv[1])
